import { SudserProfile, Booking, SudserBooking } from '@/types';

// Mock Sudsers data
export const mockSudsers: SudserProfile[] = [
  {
    id: 'sudser1',
    email: 'sarah@drip.com',
    password: 'password123',
    phone: '(555) 123-4567',
    name: 'Sarah',
    role: 'sudser',
    bio: 'Experienced launderer with 2 years of service. Let me handle your laundry stress!',
    profilePhoto: '👩',
    rating: 4.9,
    reviewCount: 87,
    hourlyRate: 18,
    services: ['wash_fold', 'delicates', 'rush'],
    availability: [
      { day: 'Monday', startTime: '4:00 PM', endTime: '8:00 PM' },
      { day: 'Tuesday', startTime: '4:00 PM', endTime: '8:00 PM' },
      { day: 'Wednesday', startTime: '4:00 PM', endTime: '8:00 PM' },
      { day: 'Thursday', startTime: '4:00 PM', endTime: '8:00 PM' },
      { day: 'Friday', startTime: '2:00 PM', endTime: '8:00 PM' },
      { day: 'Saturday', startTime: '10:00 AM', endTime: '6:00 PM' },
      { day: 'Sunday', startTime: '10:00 AM', endTime: '4:00 PM' },
    ],
    createdAt: '2024-01-15',
  },
  {
    id: 'sudser2',
    email: 'james@drip.com',
    password: 'password123',
    phone: '(555) 234-5678',
    name: 'James',
    role: 'sudser',
    bio: 'College student doing laundry on the side. Fast turnaround guaranteed!',
    profilePhoto: '👨',
    rating: 4.7,
    reviewCount: 42,
    hourlyRate: 15,
    services: ['wash_fold', 'delicates'],
    availability: [
      { day: 'Monday', startTime: '5:00 PM', endTime: '10:00 PM' },
      { day: 'Wednesday', startTime: '5:00 PM', endTime: '10:00 PM' },
      { day: 'Friday', startTime: '3:00 PM', endTime: '10:00 PM' },
      { day: 'Saturday', startTime: '9:00 AM', endTime: '8:00 PM' },
      { day: 'Sunday', startTime: '9:00 AM', endTime: '5:00 PM' },
    ],
    createdAt: '2024-02-20',
  },
  {
    id: 'sudser3',
    email: 'priya@drip.com',
    password: 'password123',
    phone: '(555) 345-6789',
    name: 'Priya',
    role: 'sudser',
    bio: 'Professional launderer. All services available including dry cleaning!',
    profilePhoto: '👱‍♀️',
    rating: 4.8,
    reviewCount: 156,
    hourlyRate: 22,
    services: ['wash_fold', 'delicates', 'dry_cleaning', 'rush'],
    availability: [
      { day: 'Monday', startTime: '9:00 AM', endTime: '5:00 PM' },
      { day: 'Tuesday', startTime: '9:00 AM', endTime: '5:00 PM' },
      { day: 'Wednesday', startTime: '9:00 AM', endTime: '5:00 PM' },
      { day: 'Thursday', startTime: '9:00 AM', endTime: '5:00 PM' },
      { day: 'Friday', startTime: '9:00 AM', endTime: '5:00 PM' },
      { day: 'Saturday', startTime: '10:00 AM', endTime: '4:00 PM' },
    ],
    createdAt: '2024-01-01',
  },
  {
    id: 'sudser4',
    email: 'deandre@drip.com',
    password: 'password123',
    phone: '(555) 456-7890',
    name: 'DeAndre',
    role: 'sudser',
    bio: 'Grew up doing laundry, love helping students! Very careful with delicates.',
    profilePhoto: '🧑',
    rating: 4.6,
    reviewCount: 23,
    hourlyRate: 14,
    services: ['wash_fold', 'delicates'],
    availability: [
      { day: 'Tuesday', startTime: '6:00 PM', endTime: '10:00 PM' },
      { day: 'Thursday', startTime: '6:00 PM', endTime: '10:00 PM' },
      { day: 'Friday', startTime: '4:00 PM', endTime: '10:00 PM' },
      { day: 'Saturday', startTime: '8:00 AM', endTime: '8:00 PM' },
      { day: 'Sunday', startTime: '1:00 PM', endTime: '6:00 PM' },
    ],
    createdAt: '2024-02-10',
  },
  {
    id: 'sudser5',
    email: 'maya@drip.com',
    password: 'password123',
    phone: '(555) 567-8901',
    name: 'Maya',
    role: 'sudser',
    bio: 'New to laundry service but very motivated and reliable!',
    profilePhoto: '👩‍🦱',
    rating: 4.5,
    reviewCount: 8,
    hourlyRate: 12,
    services: ['wash_fold'],
    availability: [
      { day: 'Monday', startTime: '3:00 PM', endTime: '9:00 PM' },
      { day: 'Wednesday', startTime: '3:00 PM', endTime: '9:00 PM' },
      { day: 'Friday', startTime: '12:00 PM', endTime: '9:00 PM' },
      { day: 'Saturday', startTime: '10:00 AM', endTime: '7:00 PM' },
    ],
    createdAt: '2024-03-05',
  },
];

// Mock test users
export const mockTestUsers = {
  sender: {
    id: 'sender1',
    email: 'sender@test.com',
    password: 'Password123',
    phone: '(555) 111-1111',
    name: 'Test Sender',
    role: 'sender' as const,
    address: '123 Main St, College Town',
    notificationsEnabled: true,
    createdAt: '2024-01-01',
  },
  sudser: {
    id: 'sudser_test',
    email: 'sudser@test.com',
    password: 'Password123',
    phone: '(555) 222-2222',
    name: 'Test Sudser',
    role: 'sudser' as const,
    bio: 'Test sudser for demo',
    rating: 4.7,
    reviewCount: 15,
    hourlyRate: 18,
    services: ['wash_fold', 'delicates', 'rush'] as const,
    availability: [
      { day: 'Monday', startTime: '4:00 PM', endTime: '8:00 PM' },
      { day: 'Friday', startTime: '2:00 PM', endTime: '8:00 PM' },
      { day: 'Saturday', startTime: '10:00 AM', endTime: '6:00 PM' },
      { day: 'Sunday', startTime: '10:00 AM', endTime: '4:00 PM' },
    ],
    createdAt: '2024-01-01',
  },
};

// Service options
export const serviceOptions = [
  {
    id: 'wash_fold' as const,
    name: 'Wash & Fold',
    description: 'Standard wash and fold service',
    basePrice: 18,
  },
  {
    id: 'delicates' as const,
    name: 'Hand Wash Delicates',
    description: 'Careful hand washing of delicate items',
    basePrice: 5,
  },
  {
    id: 'dry_cleaning' as const,
    name: 'Dry Cleaning',
    description: 'Professional dry cleaning service',
    basePrice: 3,
  },
  {
    id: 'rush' as const,
    name: 'Rush Service',
    description: 'Fast 24-hour turnaround',
    basePrice: 10,
  },
];

// Mock bookings data
export const mockBookings: Booking[] = [];
export const mockSudserBookings: SudserBooking[] = [];
